//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWord.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Word
    {
        public Nullable<int> word_id { get; set; }
        public string word_param { get; set; }
        public Nullable<System.DateTimeOffset> updated_at { get; set; }
        public Nullable<System.DateTimeOffset> deleted_at { get; set; }
        public Nullable<bool> is_deleted { get; set; }
    }
}
