//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWord.Repositories
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WordsDBEntities : DbContext
    {
        public WordsDBEntities()
            : base("name=WordsDBEntities")
        {
        }
        public WordsDBEntities(string conString)
            : base("metadata = res://*/WordsDbModel.csdl|res://*/WordsDbModel.ssdl|res://*/WordsDbModel.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=MT-5CG10579S0;initial catalog=WordsDB;integrated security=True;MultipleActiveResultSets=True;App=EntityFramework&quot;")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Word> Words { get; set; }
    }
}
